### PR TITLE
Code Review Request for Milestone 6

### PR DESCRIPTION
**Pull request by amiraabouhadid**
A foreign key for friend_id was added to enable 2 rows for each friendship pair.

### CODE REVIEW

**Comment by mke2111** [comment]
## Project is under review. It is soon coming your way.

**Review by mke2111 — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED 🔴 ♻️ 

## Hey Happy Coder, 👋🏽 
**This is a great project you have going on, well-done lad**. 

### Well-done 💯 
    1. The linter checks run just fine.
    2. The readme file is clear, concise and descriptive

**However, there are a few sections to improve before your project is approved.** 🔴 
<hr>

### REQUIRED

- [x] PostsController#index displays posts in a timeline (their own posts + posts from their friends) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/timeline.png) from Odin Project). Currently, your app is displaying all posts from all users even when they are not friends.
- [x] `friends`, `pending_friends`, `friend_requests`, `confirm_friend(user)` can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby). Good that you have added the SQL queries needed. But the ruby methods still exist.
On deleting the above methods, the app breaks while trying to access the all users page.
Remove the ruby methods and mentioned above and ensure to keep only the SQL queries you have created, and then adjust your controllers appropriately to function as expected.

### OPTIONAL

- [x] It is a good practice to have zero logic in the views directory. Create methods in the helpers directory and call the methods in the views directory instead.
Read this [article](https://medium.com/@acushla4real/rails-view-helpers-best-practices-guide-d7d7b6db3db4) for a head-start. Another great piece to read is this [article](https://brandonhilkert.com/blog/refactoring-logic-from-a-rails-view/)

#

### Kindly make all the requested changes and submit another CRR. 💯 

**Cheers 🍹 and Happy coding 💻** 

<hr>

Mention @mke2111 in this thread and I'll be glad to help. 😄 
### Best regards
Slack 🆘  Roy Mukuye
Twitter 🐦  [Roy Mukuye](https://twitter.com/Roymkenya)
LinkedIn 🔗  [Roy Mukuye](https://www.linkedin.com/in/roy-mukuye/)

**Review by SajjadAhmad14 — CHANGES_REQUESTED** [review]
# Changes Required :recycle:
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hello, you have been doing a tremendous job so far :ok_hand:
## To Highlight 🎉
- [x] Unit and Integration tests work perfectly.
- [x] You have mastered Git flow.

## To Improve 🙏
- [x] You should use Active Record Query Interface or SQL query instead of Ruby methods in friends, pending_friends, friend_requests, confirm_friend(user).

### Happy Coding ☺️

## If you have any questions you can comment here in this PR or can always connect with me on slack ( @Sajjad Ahmad ).

**Review by mke2111 — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED 🔴 ♻️ 

## Hey Happy Coder, 👋🏽 
**This is a great project you have going on, well-done lad and thanks for implementing the changes requested earlier on**. 

### Well-done 💯 
    1. The linter checks run successfully
   

**However, there are a few sections to improve before your project is approved.** 🔴 
<hr>

### REQUIRED

- [x] Use SQL queries in the user model just like you had done initially. Here is the state of your repo at `c18844d` commit. You had the SQL queries used to associate your tables within the user model.
Screenshot from 2021-05-26 17-11-28
 > Reach out to me in case you need more clarification or help with implementing this feature.


### OPTIONAL

- [x] Add the author's details to your readme file

#

### Kindly make all the requested changes and submit another CRR. 💯 

**Cheers 🍹 and Happy coding 💻** 

<hr>

Mention @mke2111 in this thread and I'll be glad to help. 😄 
### Best regards
Slack 🆘  Roy Mukuye
Twitter 🐦  [Roy Mukuye](https://twitter.com/Roymkenya)
LinkedIn 🔗  [Roy Mukuye](https://www.linkedin.com/in/roy-mukuye/)

**Review by umairarshadbutt — APPROVED** [review]
# **Status: PROJECT APPROVED** :champagne:
Excellent job on this project guys. :fireworks: Keep it up.
##
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.**
- Congratulations on the splendid job @amiraabouhadid ! :+1: 
- You can now merge to master and submit the project completion form :rocket: . I wish you all the very best in your next tasks :1st_place_medal:
##
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Pull request merged**
