### PR TITLE
Code Review Request for Milestone 5

### PR DESCRIPTION
**Pull request by amiraabouhadid**
A friendship model was created and integrated into the user model to show friendship requests, confirmed friendships, and pending friendships.

### CODE REVIEW

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @amiraabouhadid 
Such a remarkable project you made :+1: ! Awesome README :100: !
Good job with the project implementation! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed.

##

Kindly work on missing requirements as described with screenshots from Pathwright 👇.

- [x] User can invite friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/send_invitation.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x] User can see friendships requests ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/pending_request.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x] User has to accept friendship request to start friendship ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x] User can reject a friendship request ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x] There is a button to invite user to friendship on users list page and on single user page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
### [OPTIONAL]
- [x] Please add Unit and Integration tests! ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad (Code Reviewer)](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Review by SajjadAhmad14 — CHANGES_REQUESTED** [review]
# Changes Required :recycle:
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hello, Thank you for working on the changes suggested by the previous reviewer :ok_hand:
## To Highlight 🎉
- [x] You have mastered Git Flow.
- [x] PR is descriptive and professional.
## To Improve 🙏
 - [x] User should be able to cancel a friend request. It gives an error when a user tries to cancel a friendship request. See the screenshot below for reference.
cancel
- [x] There should be an invite button on the user show page and users index page. It shows now only on the user index page. Please add it on the user show page as well. 
- [x] Please add unit and Integration tests. Kindly see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png).

# Optional
- [ ] App logic should be separate from views. You can use helpers to move your logic from views.
### Happy Coding ☺️

## If you have any questions you can comment here in this PR or can always connect with me on slack ( @Sajjad Ahmad ).

**Review by SajjadAhmad14 — CHANGES_REQUESTED** [review]
# Changes Required :recycle:
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hello, you have been doing a tremendous job so far :ok_hand:

## To Improve 🙏
- [x] You have still to add integration tests for friendship functionality. Please add tests and ask for another code review.

### Happy Coding ☺️

## If you have any questions you can comment here in this PR or can always connect with me on slack ( @Sajjad Ahmad ).

**Review by SajjadAhmad14 — CHANGES_REQUESTED** [review]
# Changes Required :recycle:
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hello, you have added unit tests and that's really great :ok_hand:

## To Improve 🙏
- [x] You haven't added Integration tests yet. Please go through these [resources](https://guides.rubyonrails.org/testing.html#integration-testing) on Rails Guide to understand what are Integration tests and why they are important. KIndly add all the tests and ask for another code review!
### Happy Coding ☺️
## If you have any questions you can comment here in this PR or can always connect with me on slack ( @Sajjad Ahmad ).

**Comment by mimipeshy** [comment]
## STATUS: APPROVED 🥳 👯 
Hello team @amiraabouhadid 👋🏾 👋🏾 congratulations on making it this far in this milestone 🥇 

#### Highlights
 - You have worked on all changes requested by the previous TSE ✔️ 

With that, I approve of this project 😄 

Regards
__Peris Ndanu __
[GitHub ](https://github.com/mimipeshy)| [LinkedIn ](https://www.linkedin.com/in/peris-ndanu/)| [Twitter](https://twitter.com/pygirl254)

**Pull request merged**
